{
 "title": "Sokkel_1.1",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Circuits consumption in selected timespan",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Home\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Nede_vf_sov1_bad_wt\" or   \r\n    r._measurement == \"Nede_sov23_gang_kj_wt\"  or   \r\n    r._measurement == \"Nede_vv_tank_wt\"  or   \r\n    r._measurement == \"Nede_komfyr_wt\" or    \r\n    r._measurement == \"Oppe_vent_wt\")\r\n\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._measurement == \"Oppe_vent_wt\" or \r\n      r._measurement == \"Nede_vv_tank_wt\" \r\n      then r._value / 2.0\r\n      else r._value\r\n    }))\r\n\r\n   |> aggregateWindow(every: v.windowPeriod, fn: sum)\r\n    "
    }
   ]
  },
  {
   "title": "Total Wh in selected timespan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Home\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Nede_vf_sov1_bad_wt\"  or   \n    r._measurement == \"Nede_sov23_gang_kj_wt\"  or   \n    r._measurement == \"Nede_vv_tank_wt\"  or   \n    r._measurement == \"Nede_komfyr_wt\" or\n    r._measurement == \"Oppe_vent_wt\" )\n\n   |> map(fn: (r) => ({\n      r with\n      _value: if r._measurement == \"Oppe_vent_wt\" or \n      r._measurement == \"Nede_vv_tank_wt\" \n      then r._value / 2.0\n      else r._value\n    }))\n\n   |> aggregateWindow(every: v.windowPeriod, fn: sum)\n\n  "
    }
   ]
  },
  {
   "title": "Monthly consumption all circuits",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Home\")\r\n  |> range(start: -6mo)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Nede_vf_sov1_bad_wt\"  or   \r\n    r._measurement == \"Nede_sov23_gang_kj_wt\"  or   \r\n    r._measurement == \"Nede_vv_tank_wt\" or\r\n    r._measurement == \"Nede_komfyr_wt\"  or \r\n    r._measurement == \"Oppe_vent_wt\" )\r\n\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._measurement == \"Oppe_vent_wt\" or \r\n      r._measurement == \"Nede_vv_tank_wt\" \r\n      then r._value / 2.0\r\n      else r._value\r\n    }))\r\n\r\n   |> aggregateWindow(every: 1mo, fn: sum)\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Monthly consumption water boiler circuit ",
   "type": "barchart",
   "description": "Water boiler expenses are shared",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Home\")\r\n  |>  range(start: -6mo)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"Nede_vv_tank_wt\")\r\n\r\n   |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._measurement == \"Oppe_vent_wt\" or \r\n      r._measurement == \"Nede_vv_tank_wt\" \r\n      then r._value / 2.0\r\n      else r._value\r\n    }))\r\n\r\n   |> aggregateWindow(every: 1mo, fn: sum)\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Electricity prices",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyNOK" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\nfrom(bucket: \"Home\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"pw_price_nok\")\r\n\r\n\r\n   |> aggregateWindow(every: 1h, fn: sum)\r\n    "
    }
   ]
  },
  {
   "title": "Wh water boiler in selected timespan",
   "type": "gauge",
   "description": "Water boiler expenses are shared",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Home\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Nede_vv_tank_wt\")\n\n  |> map(fn: (r) => ({\n      r with\n      _value: if r._measurement == \"Oppe_vent_wt\" or \n      r._measurement == \"Nede_vv_tank_wt\" \n      then r._value / 2.0\n      else r._value\n    }))\n\n   |> aggregateWindow(every: v.windowPeriod, fn: sum)\n\n  "
    }
   ]
  }
 ]
}